# docker-compose.yml
name: monitoring
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring  # 네트워크

  prometheus-push-gateway:
    image : prom/pushgateway:latest
    container_name: prometheus-push-gateway
    ports:
      - "9091:9091"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring  # 네트워크

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - monitoring  # 네트워크
    environment:
      - GF_SECURITY_ADMIN_USER=admin  # Grafana 기본 사용자명
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Grafana 기본 비밀번호
    volumes:
      - ./provisioning:/etc/grafana/provisioning

networks:
  monitoring:
    driver: bridge

volumes:
  grafana-storage:  # ✅ 정의 추가