spring:
  application:
    name: actuator
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/actuator?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

server:
  port: 7777
  tomcat:
    mbeanregistry:
      enabled: true # tomcat과 관련된 Endpoint를 노출한다.

management:
  endpoints:
    web:
      exposure:
        include: "*"
#    prometheus:
#      enabled: true